### ISSUE TITLE
The click on block doesn't work in the Visual Editor

### ISSUE THREAD

**Issue by wesssel** [storyblok/nuxt-ultimate-tutorial#6]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When using this great template, everything seems to work except when clicking on a block in the visual editor, the block doesn't open in the right sidebar

---

## Expected Behavior

Would be great to have the clicked block opened in the right sidebar on click in the visual editor.

## Current Behavior

When clicking on the block, nothing happens.

## Steps to Reproduce

1. Create a new space
2. Copy the `npx @storyblok/create-demo@latest --key KEY_EXAMPLE` code and run locally 
3. Select Nuxt3
4. Run the project locally
5. Enable the visual editor in Storyblok
6. Open `home` in the content tab 
7. Click on an element

**Comment by Dawntraoz** [comment]
Closing since this is working in the latest versions (old issue)
